# Generated by Django 4.2.6 on 2023-11-08 20:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journeyingblogs', '0002_topic_chamber_host_message_chamber_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chamber',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='chamber',
            name='techiesspace',
            field=models.ManyToManyField(blank=True, related_name='techiesspace', to=settings.AUTH_USER_MODEL),
        ),
    ]
